version: '3'

networks:
  desafionet:
    driver: bridge

volumes:
  mysql_data:
    driver: local
    driver_opts:
      type: none
      device: mysql
      o: bind

services:
  mysql:
    image: mysql:5.7.16
    container_name: database
    environment:
      - "MYSQL_ROOT_PASSWORD=root"
      - "MYSQL_DATABASE=appdb"
      - "MYSQL_USER=appuser"
      - "MYSQL_PASSWORD=apppass"
    tty: true
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - desafionet

  node:
    build: 
      context: ./
      dockerfile: Dockerfile-node
    image: node
    container_name: node
    environment:
      - db_host=mysql
      - db_name=appdb
      - db_user=root
      - db_pass=root
    tty: true
    depends_on:
      - mysql
    restart: on-failure
    entrypoint: dockerize -wait tcp://mysql:3306 -timeout 20s
    command: node index.js
    networks:
      - desafionet

  nginx:
    build: 
      context: ./
      dockerfile: Dockerfile-nginx
    image: nginx
    container_name: nginx
    ports:
      - 8080:80
    tty: true
    depends_on:
      - node
    entrypoint: dockerize -wait tcp://node:3000 -timeout 20s
    command: nginx -g 'daemon off;'
    restart: on-failure
    networks:
      - desafionet