version: '3'

networks:
  desafionet:
    driver: bridge

services:
  mysql:
    image: mysql:5.7
    container_name: database
    environment:
      - "MYSQL_ROOT_PASSWORD=root"
      - "MYSQL_DATABASE=appdb"
      - "MYSQL_USER=appuser"
      - "MYSQL_PASSWORD=apppass"
    tty: true
    networks:
      - desafionet

  node:
    build: 
      context: ./
      dockerfile: Dockerfile-node
    image: node
    container_name: node
    environment:
      - db_host=mysql
      - db_name=appdb
      - db_user=root
      - db_pass=root
    tty: true
    depends_on:
      - mysql
    restart: on-failure
    networks:
      - desafionet

  nginx:
    build: 
      context: ./
      dockerfile: Dockerfile-nginx
    image: nginx
    container_name: nginx
    ports:
      - 8080:80
    tty: true
    restart: on-failure
    networks:
      - desafionet