version: '3'

networks:
  desafionet:
    driver: bridge

services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      - "MYSQL_ROOT_PASSWORD=root"
      - "MYSQL_DATABASE=appdb"
      - "MYSQL_USER=appuser"
      - "MYSQL_PASSWORD=apppass"
    tty: true
    networks:
      - desafionet